[package]
name = "destiny-rs-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.9", features=["blocking"]}
regex = "1.5.4"
lazy_static = "1.4.0"
