name: Rust build/unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Load manifest cache
        uses: actions/cache@v2
        env:
          cache-name: destiny-manifest-cache
        with:
          path: ~/.local/share/destiny-rs
          key: destiny-manifest-cache
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Download manifest
        run: cargo run --bin manifest_downloader
        env:
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
      - name: Run tests
        run: cargo test -- --nocapture
        env:
          RUST_LOG: trace
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
