name: Rust build/unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build

      - name: Get manifest URL
        run: cargo run --bin manifest-downloader -- --ci-output-manifest-url
        env:
          RUST_LOG: info
          CI_OUTPUT_MANIFEST_URL_FILE: ~/manifest-url/url.txt
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}

      - name: Load manifest cache
        uses: actions/cache@v2
        env:
          cache-name: destiny-manifest-cache
        with:
          path: ~/.local/share/destiny-rs
          key: destiny-manifest-cache-${{ hashFiles('~/manifest-url/url.txt') }}

      - uses: actions/checkout@v2
      - name: Download manifest
        run: cargo run --bin manifest-downloader
        env:
          RUST_LOG: info
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}

      - name: Run tests
        run: cargo test -- --nocapture
        env:
          RUST_LOG: trace
          BUNGIE_API_KEY: ${{ secrets.BUNGIE_API_KEY }}
