name: Rust build/unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  runs-on: [ 'ubuntu-latest' ]
  
  steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test -- --nocapture
      env:
        RUST_LOG=trace
